### ISSUE TITLE
Getting python path

### ISSUE THREAD

**Issue by rashomon-gh** [maacpiash/PythonScriptRunner#2]
Rather than hardcoding the python path in the program, **the program should get the python path from the system path variables**. Makes it easier for the user to use the program.

**Comment by maacpiash** [comment]
I know I need to do that, because this program has to run on other people's computers. I'm looking for a solution to this problem.

**Comment by maacpiash** [comment]
Solved the issue. Took only 16 months. No big deal ¯\\_(ツ)_/¯

**Comment by shawonashraf** [comment]
Never expected it faster from you 👍

**Comment by maacpiash** [comment]
You will be happy to know that now it runs cross-platform! Go ahead, give it a test (if you have time to spare, of course) and let me know if something goes wrong :relaxed:

**Comment by shawonashraf** [comment]
Okay.
